remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme 

title: Power365 Blogs
description: This blog lays a spotlight on technical know-how of Power Platform and D365 Fin&Ops implementations, customizations and other technial and functional titbits.