remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme 

title: Power365 Blogs
description: This blog highlights the technical aspects of implementing and customizing Power Platform and D365 Finance & Operations which serves as a guide when required for makers, developers and business users